using Account.Application.Commands.CreateAccount;
using Account.Application.Repositories;
using Microsoft.Extensions.Logging;
using Moq;
using Shared.Common.Persistence;
using Shared.Common.ValueObjects;
using AccountEntity = Account.Domain.Entities.Account;

namespace Account.Application.Tests.Commands;

public sealed class CreateAccountCommandHandlerTests
{
    private readonly Mock<IAccountRepository> _mockAccountRepository;
    private readonly Mock<IUnitOfWork> _mockUnitOfWork;
    private readonly Mock<ILogger<CreateAccountCommandHandler>> _mockLogger;
    private readonly CreateAccountCommandHandler _handler;

    public CreateAccountCommandHandlerTests()
    {
        _mockAccountRepository = new Mock<IAccountRepository>();
        _mockUnitOfWork = new Mock<IUnitOfWork>();
        _mockLogger = new Mock<ILogger<CreateAccountCommandHandler>>();

        _handler = new CreateAccountCommandHandler(
            _mockAccountRepository.Object,
            _mockUnitOfWork.Object,
            _mockLogger.Object);
    }

    [Fact]
    public async Task Handle_WithValidCommand_CreatesAccountWithAutoGeneratedIban()
    {
        var command = new CreateAccountCommand
        {
            InitialBalance = 1000,
            Currency = "USD",
            OwnerId = "user-123"
        };

        _mockAccountRepository
            .Setup(x => x.GetByIbanAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((AccountEntity?) null);

        var result = await _handler.Handle(command, CancellationToken.None);

        Assert.NotNull(result);
        Assert.NotEqual(Guid.Empty, result.AccountId);
        Assert.NotEmpty(result.Iban);
        Assert.StartsWith("TR", result.Iban); // Turkish IBAN

        _mockAccountRepository.Verify(
            x => x.AddAsync(It.IsAny<AccountEntity>(), It.IsAny<CancellationToken>()),
            Times.Once);

        _mockUnitOfWork.Verify(
            x => x.SaveChangesAsync(It.IsAny<CancellationToken>()),
            Times.Once);
    }

    [Fact]
    public async Task Handle_WithDuplicateIban_RetriesAndGeneratesNewIban()
    {
        var command = new CreateAccountCommand
        {
            InitialBalance = 1000,
            Currency = "USD",
            OwnerId = "user-123"
        };

        var existingAccount = AccountEntity.Create(
            Guid.NewGuid(),
            IBAN.Create("TR330006100519786457841326"),
            Money.Create(500, Currency.Create("USD")),
            "user-456");

        _mockAccountRepository
            .SetupSequence(x => x.GetByIbanAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(existingAccount)
            .ReturnsAsync((AccountEntity?) null);

        var result = await _handler.Handle(command, CancellationToken.None);

        Assert.NotNull(result);
        Assert.NotEmpty(result.Iban);
        Assert.StartsWith("TR", result.Iban);

        _mockAccountRepository.Verify(
            x => x.GetByIbanAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()),
            Times.Exactly(2));
    }

    [Fact]
    public async Task Handle_WithNegativeBalance_ThrowsException()
    {
        var command = new CreateAccountCommand
        {
            InitialBalance = -100,
            Currency = "USD",
            OwnerId = "user-123"
        };

        await Assert.ThrowsAsync<ArgumentException>(() => _handler.Handle(command, CancellationToken.None));

        _mockAccountRepository.Verify(
            x => x.AddAsync(It.IsAny<AccountEntity>(), It.IsAny<CancellationToken>()),
            Times.Never);
    }
}